<?php

namespace helper;

class AmazonTemplateUK extends AmazonTemplate
{
    private static $header = [
        [
            'TemplateType=Shoes',
            'Version=2015.1020',
            ['The top 3 rows are for Amazon.com use only. Do not modify or delete the top 3 rows.', 'C1', 'J1'],
            ['Offer - Offer Information - These attributes are required to make your item buyable for customers on the site.', 'K1', 'V1'],
            ['Dimensions - Product Dimensions - These attributes specify the size and weight of a product.', 'W1', 'AD1'],
            ['Discovery - Item discovery information - These attributes have an effect on how customers can find your product on the site using browse or search.', 'AE1', 'AP1'],
            ['Images - Image Information - See Image Instructions tab for details.', 'AQ1', 'AZ1'],
            ['Fulfillment - Use these columns to provide fulfilment-related information for orders fulfilled either by Amazon (FBA) or by the Seller.', 'BA1', 'BG1'],
            ['Variation - Variation information - Populate these attributes if your product is available in different variations (for example colour or wattage).', 'BH1', 'BK1'],
            ['Compliance - Compliance Information - Attributes used to comply with consumer laws in the country or region where the item is sold.', 'BL1', 'BM1'],
            ['Ungrouped - These attributes create rich product listings for your buyers.', 'BN1', 'CU1'],
        ],
        [
            'Seller SKU',
            'Product ID',
            'Product ID Type',
            'Product Name',
            'Brand',
            'Product Description',
            'Product Type',
            'Update Delete',
            'Manufacturer part number',
            'Model number',
            'Standard Price',
            'Currency',
            'Quantity',
            'Sale Price',
            'Sale From Date',
            'Sale End Date',
            'Item Package Quantity',
            'Can Be Gift Messaged',
            'Is Gift Wrap Available?',
            'Is Discontinued By Manufacturer',
            'Fulfillment Latency',
            'Merchant Shipping Group',
            'Website Shipping Weight Unit Of Measure',
            'Shipping Weight',
            'Item Length',
            'Item Height',
            'Item Width',
            'Item Dimensions Unit Of Measure',
            'Item Weight',
            'Unit Of Measure Of Item Weight',
            'Recommended Browse Node1',
            'Recommended Browse Node2',
            'Search Terms1',
            'Search Terms2',
            'Search Terms3',
            'Search Terms4',
            'Search Terms5',
            'Platinum Keywords1',
            'Platinum Keywords2',
            'Platinum Keywords3',
            'Platinum Keywords4',
            'Platinum Keywords5',
            'Main Image URL',
            'Other Image URL1',
            'Other Image URL2',
            'Other Image URL3',
            'Other Image URL4',
            'Other Image URL5',
            'Other Image URL6',
            'Other Image URL7',
            'Other Image URL8',
            'Swatch Image Url',
            'Package Height',
            'Package Width',
            'Package Length',
            'Package Dimensions Unit Of Measure',
            'Package Weight',
            'Package Weight Unit Of Measure',
            'Fulfillment Centre ID',
            'Parentage',
            'Parent SKU',
            'Relationship Type',
            'Variation Theme',
            'Country Of Origin',
            'EU Toys Safety Directive Non-Age-specific warning',
            'Department',
            'Model Name',
            'Strap Type',
            'Model Year',
            'Style Name',
            'Colour',
            'Colour Map',
            'size',
            'Size Map',
            'Material Composition',
            'Inner Material Type',
            'Outer Material Type',
            'Insole Type',
            'Leather Type',
            'Sole Material',
            'Collection',
            'Season',
            'Heel Type',
            'Heel Height',
            'Shaft Height',
            'Shaft Diameter',
            'Platform Height',
            'Shoe Width',
            'Closure Type',
            'Arch Type',
            'Water Resistance Level',
            'Cleat Description',
            'Pronation Correction',
            'Sport Type',
            'Surface Recommendation',
            'Shoe Safety Code ISO 20345',
            'Lining Description',
            'Heel Height Unit Of Measure',
            'Shoulder Strap Drop',
        ],
        [
            'item_sku',
            'external_product_id',
            'external_product_id_type',
            'item_name',
            'brand_name',
            'product_description',
            'feed_product_type',
            'update_delete',
            'part_number',
            'model',
            'standard_price',
            'currency',
            'quantity',
            'sale_price',
            'sale_from_date',
            'sale_end_date',
            'item_package_quantity',
            'offering_can_be_gift_messaged',
            'offering_can_be_giftwrapped',
            'is_discontinued_by_manufacturer',
            'fulfillment_latency',
            'merchant_shipping_group_name',
            'website_shipping_weight_unit_of_measure',
            'website_shipping_weight',
            'item_length',
            'item_height',
            'item_width',
            'item_dimensions_unit_of_measure',
            'item_weight',
            'item_weight_unit_of_measure',
            'recommended_browse_nodes1',
            'recommended_browse_nodes2',
            'generic_keywords1',
            'generic_keywords2',
            'generic_keywords3',
            'generic_keywords4',
            'generic_keywords5',
            'platinum_keywords1',
            'platinum_keywords2',
            'platinum_keywords3',
            'platinum_keywords4',
            'platinum_keywords5',
            'main_image_url',
            'other_image_url1',
            'other_image_url2',
            'other_image_url3',
            'other_image_url4',
            'other_image_url5',
            'other_image_url6',
            'other_image_url7',
            'other_image_url8',
            'swatch_image_url',
            'package_height',
            'package_width',
            'package_length',
            'package_dimensions_unit_of_measure',
            'package_weight',
            'package_weight_unit_of_measure',
            'fulfillment_center_id',
            'parent_child',
            'parent_sku',
            'relationship_type',
            'variation_theme',
            'country_of_origin',
            'eu_toys_safety_directive_warning',
            'department_name',
            'model_name',
            'strap_type',
            'model_year',
            'style_name',
            'color_name',
            'color_map',
            'size_name',
            'size_map',
            'material_composition',
            'inner_material_type',
            'outer_material_type',
            'insole_type',
            'leather_type',
            'sole_material',
            'collection_name',
            'seasons',
            'heel_type',
            'heel_height',
            'shaft_height',
            'shaft_diameter',
            'platform_height',
            'shoe_width',
            'closure_type',
            'arch_type',
            'water_resistance_level',
            'cleat_description',
            'pronation_correction',
            'sport_type',
            'surface_recommendation',
            'shoe_safety_code_iso_20345',
            'lining_description',
            'heel_height_unit_of_measure',
            'shoulder_strap_drop',
        ]
    ];
}
