<?php

namespace helper;

class AmazonTemplateDE extends AmazonTemplate
{
    private static $header = [
        [
            'TemplateType=Shoes',
            'Version=2015.0319',
            ['Die oberen drei Zeilen sind nur zur Verwendung durch Amazon.de vorgesehen. Veraendern oder loeschen Sie die obersten drei Zeilen nicht.', 'C1', 'J1'],
            ['Angebot - Informationen zum Angebot - Diese Attribute werden benoetigt, um Ihren Artikel fuer Kunden auf der Website kaeuflich zu machen.', 'K1', 'W1'],
            ['Abmessungen - Produktabmessungen - Diese Attribute geben die Groesse und das Gewicht eines Produktes an.', 'X1', 'AE1'],
            ['Artikelerkennungs - Artikelerkennungsinformationen - Diese Attribute haben einen Einfluss darauf, wie Kunden Ihr Produkt mittels Durchsuchen oder Suchfunktionen auf der Website finden.', 'AF1', 'AQ1'],
            ['Bild - Bildinformationen - Weitere Informationen finden Sie auf der Registerkarte Bildanweisungen.', 'AR1', 'BA1'],
            ['Versand - Verwenden Sie diese Spalten, um Informationen zu Bestellungen bereitzustellen, die durch Versand durch Amazon oder durch den Verkaeufer versendet werden.', 'BB1', 'BH1'],
            ['Variations - Variationsinformationen - Fuellen Sie diese Attribute aus, wenn Ihr Produkt in verschiedenen Ausfuehrungen (z. B. Farben oder Stromstaerken) erhaeltlich ist.', 'BI1', 'BL1'],
            ['Konformitaets - Konformitaetsinformationen - Attribute, die zur uebereinstimmung mit Verbrauchergesetzen in dem Land oder in der Region erforderlich sind, wo der Artikel verkauft wird.', 'BM1', 'BN1'],
            ['Ungruppiert - Diese Attribute erzeugen reichhaltige Produktangebote für Ihre Kunden.', 'BO1', 'CV1'],
        ],
        [
            'Lagerhaltungsnummer',
            'Hersteller-Barcode',
            'Barcode-Typ',
            'Produktname',
            'Marke',
            'Produktbeschreibung',
            'Produkttyp',
            'Update / Loeschen',
            'Artikelnummer des Herstellers',
            'Modellnummer',
            'SKU-Liste für Lieferung zum Wunschtermin',
            'Preis',
            'Waehrung',
            'Anzahl',
            'Angebotspreis',
            'Startdatum des Sonderangebots',
            'Enddatum des Sonderangebots',
            'Kaufeinheit',
            'Geschenknachricht moeglich?',
            'Kann Artikel als Geschenk verpackt werden?',
            'Produktion des Artikels eingestellt?',
            'Vorlaufzeit für die Lieferung',
            'Verkaeuferversandgruppe',
            'Produktlaenge',
            'Produkthoehe',
            'Produktbreite',
            'Produkt Dimensionsmass',
            'Masseinheit des auf der Webseite angegebenen Versandgewichts',
            'Versandgewicht',
            'Artikelgewicht',
            'Masseinheit für das Artikelgewicht',
            'Empfohlene Klassifikationsnummer1',
            'Empfohlene Klassifikationsnummer2',
            'Suchbegriffe1',
            'Suchbegriffe2',
            'Suchbegriffe3',
            'Suchbegriffe4',
            'Suchbegriffe5',
            'Platinum-Schlüsselwoerter1',
            'Platinum-Schlüsselwoerter2',
            'Platinum-Schlüsselwoerter3',
            'Platinum-Schlüsselwoerter4',
            'Platinum-Schlüsselwoerter5',
            'URL Hauptbild',
            'URL Weiteres Produktbild1',
            'URL Weiteres Produktbild2',
            'URL Weiteres Produktbild3',
            'URL Weiteres Produktbild4',
            'URL Weiteres Produktbild5',
            'URL Weiteres Produktbild6',
            'URL Weiteres Produktbild7',
            'URL Weiteres Produktbild8',
            'URL Musterbild',
            'Pakethoehe',
            'Paketbreite',
            'Paketlaenge',
            'Masseinheit der Verpackungsmasse',
            'Paketgewicht',
            'Masseinheit des Verpackungsgewichts',
            'Versandzentrum-ID',
            'Variantenbestandteil',
            'SKU des übergeordneten Produkts',
            'Produktbeziehungs-Typ',
            'Varianten-Design',
            'Herstellungsland',
            'Nicht altersspezifische Sicherheitswarnung der EU für Spielzeug',
            'Modellbezeichnung',
            'Abteilung',
            'Stilbezeichnung',
            'Farbe',
            'Farbschema',
            'Schuhgroesse',
            'Groessenschema',
            'Textilkennzeichnung',
            'Innenmaterial',
            'Oberflaechenmaterial',
            'Sohlenart',
            'Lederart',
            'Sohlenmaterial',
            'Kollektion',
            'Saison',
            'Absatzform',
            'Absatzhoehe',
            'Schuh-spezifisches Dimensionsmass',
            'Schafthoehe',
            'Schaftweite',
            'Plattformhoehe',
            'Schuhbreite',
            'Verschlussart',
            'Fussgewoelbehoehe',
            'Wasserfestigkeit',
            'Spiketyp (Stollentyp)',
            'Pronationskorrektur',
            'Geeignete Sportart',
            'Geeignete Gelaendeart',
            'Sicherheitscode nach ISO Norm 20345',
            'Innenfutter',
            'StrapType',
            'Modelljahr',
            'Riemenlaenge',
        ],
        [
            'item_sku',
            'external_product_id',
            'external_product_id_type',
            'item_name',
            'brand_name',
            'product_description',
            'feed_product_type',
            'update_delete',
            'part_number',
            'model',
            'delivery_schedule_group_id',
            'standard_price',
            'currency',
            'quantity',
            'sale_price',
            'sale_from_date',
            'sale_end_date',
            'item_package_quantity',
            'offering_can_be_gift_messaged',
            'offering_can_be_giftwrapped',
            'is_discontinued_by_manufacturer',
            'fulfillment_latency',
            'merchant_shipping_group_name',
            'item_length',
            'item_height',
            'item_width',
            'item_dimensions_unit_of_measure',
            'website_shipping_weight_unit_of_measure',
            'website_shipping_weight',
            'item_weight',
            'item_weight_unit_of_measure',
            'recommended_browse_nodes1',
            'recommended_browse_nodes2',
            'generic_keywords1',
            'generic_keywords2',
            'generic_keywords3',
            'generic_keywords4',
            'generic_keywords5',
            'platinum_keywords1',
            'platinum_keywords2',
            'platinum_keywords3',
            'platinum_keywords4',
            'platinum_keywords5',
            'main_image_url',
            'other_image_url1',
            'other_image_url2',
            'other_image_url3',
            'other_image_url4',
            'other_image_url5',
            'other_image_url6',
            'other_image_url7',
            'other_image_url8',
            'swatch_image_url',
            'package_height',
            'package_width',
            'package_length',
            'package_dimensions_unit_of_measure',
            'package_weight',
            'package_weight_unit_of_measure',
            'fulfillment_center_id',
            'parent_child',
            'parent_sku',
            'relationship_type',
            'variation_theme',
            'country_of_origin',
            'eu_toys_safety_directive_warning',
            'model_name',
            'department_name',
            'style_name',
            'color_name',
            'color_map',
            'size_name',
            'size_map',
            'material_composition',
            'inner_material_type',
            'outer_material_type',
            'insole_type',
            'leather_type',
            'sole_material',
            'collection_name',
            'seasons',
            'heel_type',
            'heel_height',
            'heel_height_unit_of_measure',
            'shaft_height',
            'shaft_diameter',
            'platform_height',
            'shoe_width',
            'closure_type',
            'arch_type',
            'water_resistance_level',
            'cleat_description',
            'pronation_correction',
            'sport_type',
            'surface_recommendation',
            'shoe_safety_code_iso_20345',
            'lining_description',
            'strap_type',
            'model_year',
            'shoulder_strap_drop',
        ],
    ];
}
